-- --- 1. SAFE TABLE MIGRATIONS ---
-- This section creates tables if they don't exist, and adds columns if they are missing.

-- Services Table
CREATE TABLE IF NOT EXISTS services (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Draft';
ALTER TABLE services ADD COLUMN IF NOT EXISTS pills JSONB DEFAULT '[]'::jsonb;
ALTER TABLE services ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS meta_description TEXT;

-- Blog Posts Table
CREATE TABLE IF NOT EXISTS posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE posts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Draft';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS meta_description TEXT;

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS slug TEXT;

-- Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS designation TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS service_name TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS review TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS stars INTEGER DEFAULT 5;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';

-- Case Studies Table
CREATE TABLE IF NOT EXISTS case_studies (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS client TEXT;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE case_studies ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Draft';

-- Leads Table
CREATE TABLE IF NOT EXISTS leads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mobile_number TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS project_budget TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS project_details TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'New';

-- --- 2. SECURITY POLICIES (TABLES) ---

ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_studies ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Services Policies
DROP POLICY IF EXISTS "Public services are viewable by everyone" ON services;
CREATE POLICY "Public services are viewable by everyone" ON services FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert services" ON services;
CREATE POLICY "Authenticated users can insert services" ON services FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update services" ON services;
CREATE POLICY "Authenticated users can update services" ON services FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete services" ON services;
CREATE POLICY "Authenticated users can delete services" ON services FOR DELETE USING (auth.role() = 'authenticated');

-- Posts Policies
DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON posts;
CREATE POLICY "Public posts are viewable by everyone" ON posts FOR SELECT USING (status = 'Published' OR auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can manage posts" ON posts;
CREATE POLICY "Authenticated users can manage posts" ON posts FOR ALL USING (auth.role() = 'authenticated');

-- Categories Policies
DROP POLICY IF EXISTS "Public categories are viewable by everyone" ON categories;
CREATE POLICY "Public categories are viewable by everyone" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can manage categories" ON categories;
CREATE POLICY "Authenticated users can manage categories" ON categories FOR ALL USING (auth.role() = 'authenticated');

-- Testimonials Policies
DROP POLICY IF EXISTS "Public testimonials are viewable by everyone" ON testimonials;
CREATE POLICY "Public testimonials are viewable by everyone" ON testimonials FOR SELECT USING (status = 'Active' OR auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can manage testimonials" ON testimonials;
CREATE POLICY "Authenticated users can manage testimonials" ON testimonials FOR ALL USING (auth.role() = 'authenticated');

-- Case Studies Policies
DROP POLICY IF EXISTS "Public case studies are viewable by everyone" ON case_studies;
CREATE POLICY "Public case studies are viewable by everyone" ON case_studies FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can manage case studies" ON case_studies;
CREATE POLICY "Authenticated users can manage case studies" ON case_studies FOR ALL USING (auth.role() = 'authenticated');

-- Leads Policies
DROP POLICY IF EXISTS "Enable insert for everyone" ON leads;
CREATE POLICY "Enable insert for everyone" ON leads FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable access for authenticated users only" ON leads;
CREATE POLICY "Enable access for authenticated users only" ON leads FOR ALL USING (auth.role() = 'authenticated');


-- --- 3. STORAGE SETUP (Buckets & Policies) ---

-- Create a 'media' bucket for images
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Allow public access to view images
DROP POLICY IF EXISTS "Public Access Media" ON storage.objects;
CREATE POLICY "Public Access Media"
ON storage.objects FOR SELECT
USING ( bucket_id = 'media' );

-- Allow authenticated users to upload
DROP POLICY IF EXISTS "Auth Upload Media" ON storage.objects;
CREATE POLICY "Auth Upload Media"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'media' AND auth.role() = 'authenticated' );

-- Allow authenticated users to update
DROP POLICY IF EXISTS "Auth Update Media" ON storage.objects;
CREATE POLICY "Auth Update Media"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'media' AND auth.role() = 'authenticated' );

-- Allow authenticated users to delete
DROP POLICY IF EXISTS "Auth Delete Media" ON storage.objects;
CREATE POLICY "Auth Delete Media"
ON storage.objects FOR DELETE
USING ( bucket_id = 'media' AND auth.role() = 'authenticated' );
