
-- Ensure the testimonials table exists
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  business_name TEXT,
  service_name TEXT,
  review TEXT NOT NULL,
  stars INTEGER DEFAULT 5,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Archived'))
);

-- Enable RLS
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Public view testimonials" ON testimonials;
CREATE POLICY "Public view testimonials" ON testimonials FOR SELECT USING (status = 'Active');

DROP POLICY IF EXISTS "Admins manage testimonials" ON testimonials;
CREATE POLICY "Admins manage testimonials" ON testimonials FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'manager'))
);

-- Seed Data (Static content from Home Page)
INSERT INTO testimonials (name, business_name, service_name, review, stars, status) VALUES
-- Email Marketing
('Jonas Wadel', 'Founder, E-com Collective', 'Email Marketing & Automation', 'Working with this team changed our entire retention strategy. They didn''t just set up email flows; they built a high-converting revenue engine. We’ve seen a massive jump in recovered carts since the launch. Truly a professional with deep knowledge.', 5, 'Active'),
('Thomas Poppa', 'Marketing Director', 'Email Marketing & Automation', 'The communication was exceptional, but the results were even better. They took our messy email list and turned it into an automated profit center. If you need someone who understands the technical side of email marketing, look no further.', 5, 'Active'),
('Brittany Miller', 'CEO, Glow Brands', 'Email Marketing & Automation', 'Simply the best. They mapped out our entire customer journey and implemented flows that actually feel personal to our users. Our repeat purchase rate has never been higher. Highly recommended for any serious brand.', 5, 'Active'),
('Edward Sullivan', 'Operations Manager', 'Email Marketing & Automation', 'Exceptional work! They simplified a very complex automation task for us. Their knowledge of email deliverability and design is top-tier. A great professional who delivers exactly what is promised, and then some.', 5, 'Active'),
('Dionne Richards', 'Founder, Lifestyle Co.', 'Email Marketing & Automation', 'Clear communication and incredible execution. They built a lifecycle marketing system that works while we sleep. It''s rare to find an agency that understands both the creative and the data-driven side of marketing so well.', 5, 'Active'),

-- Web Design
('Muhammad Afzaal', 'Tech Lead', 'Web Design & Development', 'Our new site is lightning fast and looks incredible. They took our vision and engineered a web experience that has already improved our conversion rate by 40%. Great work and very communicative throughout the process.', 5, 'Active'),
('Uzma Khan', 'Creative Director', 'Web Design & Development', 'They handled our complex web development needs with total ease. Even when we ran into heavy workloads, they remained professional and delivered a high-performance site that exceeds our expectations. Highly recommended!', 5, 'Active'),
('Daniel Townes', 'Startup Founder', 'Web Design & Development', 'A truly professional experience. They didn''t just build a website; they built a digital storefront that sells. Their knowledge of modern web architecture is evident in the final product. Speed, SEO, and style—they nailed it all.', 5, 'Active'),
('Sarah Pointer', 'E-commerce Manager', 'Web Design & Development', 'Great and fast! They turned our outdated site into a modern, responsive powerhouse. The transition was seamless, and the code is remarkably clean. We will definitely be back for our future development projects.', 5, 'Active'),
('Brooklyn Wilson', 'Managing Partner', 'Web Design & Development', 'Communication was great, but the final build was even better. They have a unique ability to blend technical development with a high-end design aesthetic. Looking forward to working together on the next phase of our growth.', 5, 'Active'),

-- UI/UX
('Marcus Sterling', 'Head of Product', 'UI/UX Design', 'The UI/UX work was transformative. They identified friction points we didn''t even know existed and redesigned our user flow to be incredibly intuitive. The design is clean, modern, and perfectly aligned with our brand.', 5, 'Active'),
('Elena Vance', 'App Founder', 'UI/UX Design', 'They have a deep understanding of human-centric design. Our new interface isn''t just beautiful; it''s functional and easy to navigate. They truly turned our concept into a world-class digital product.', 5, 'Active'),
('Julian Thorne', 'CEO, Fintech Solutions', 'UI/UX Design', 'Highly professional design process. From wireframes to high-fidelity prototypes, every step was handled with precision. They created a design system that is scalable and absolutely stunning.', 5, 'Active'),
('Sarah Jenkins', 'Marketing Lead', 'UI/UX Design', 'They took our rough ideas and polished them into a high-end user experience. Their attention to detail in the UI elements is what sets them apart from other agencies. An amazing partner for any creative project.', 5, 'Active'),
('Robert Chen', 'CTO', 'UI/UX Design', 'The UI/UX strategy they delivered helped us secure our next round of funding. Investors were blown away by the clarity and professionalism of the interface. Exceptional knowledge and execution.', 5, 'Active'),

-- iOS App
('David Rossi', 'Founder, HealthTech App', 'iOS App Development', 'The technical precision of our iOS app is outstanding. It’s fast, stable, and follows all of Apple’s latest HIG standards. They turned a complex set of features into a seamless mobile experience.', 5, 'Active'),
('Lisa Kensington', 'Product Manager', 'iOS App Development', 'Working with this team on our native iOS app was the best decision we made. The communication was constant, and the technical execution was flawless. They truly know how to build for the App Store.', 5, 'Active'),
('Michael Park', 'Tech Entrepreneur', 'iOS App Development', 'Clean code, great architecture, and a beautiful front-end. They handled everything from API integration to the final deployment. Our app is scaling perfectly, and user feedback has been 100% positive.', 5, 'Active'),
('Karen Wu', 'Director of Innovation', 'iOS App Development', 'They delivered our iOS project ahead of schedule and with zero bugs. Their ability to solve complex technical problems on the fly is impressive. If you want a native app done right, this is the agency.', 5, 'Active'),
('Alex Turner', 'Founder, Social Ventures', 'iOS App Development', 'From initial consultation to the App Store launch, the journey was perfect. They are not just developers; they are strategic partners who care about the success of your product. Five stars all the way.', 5, 'Active');
