name: infobytes
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_AIRTABLE_BASE_ID
        value: app4HU1eGrqtRzFen
      - key: VITE_AIRTABLE_API_TOKEN
        value: "${VITE_AIRTABLE_API_TOKEN}"
